### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nicnicknicky** [nicnicknicky/pimp-my-raspbian#11]
- [ ] Cleanup ugly building logs
- [ ] xdotool: refresh/rotate tabs automatically
- [ ] wlan0 connectivity check
- [ ] README: Include prebuild steps
- [ ] Differentiate for graphical/lite installs
- [ ] Fix crontab error
